"""initial inventory schema

Revision ID: 0001
Revises:
Create Date: 2026-09-28 16:29:55.532786
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("state", sa.String(length=64), nullable=True),
        sa.Column("country", sa.String(length=64), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "firewall", "switch", "access_point", "server", "telephony", "other", name="device_category"
            ),
            nullable=False,
        ),
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column("management_ip", sa.String(length=45), nullable=True),
        sa.Column("vendor", sa.String(length=120), nullable=True),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column("serial_number", sa.String(length=120), nullable=True),
        sa.Column("firmware_version", sa.String(length=120), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "spare", "maintenance", "decommissioned", name="lifecycle_status"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("librenms_device_id", sa.Integer(), nullable=True),
        sa.Column("prtg_object_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("serial_number"),
    )
    op.create_index(op.f("ix_devices_site_id"), "devices", ["site_id"], unique=False)
    op.create_table(
        "internet_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=120), nullable=False),
        sa.Column("circuit_id", sa.String(length=120), nullable=True),
        sa.Column("technology", sa.String(length=64), nullable=True),
        sa.Column("bandwidth_mbps", sa.Integer(), nullable=True),
        sa.Column("public_ip", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "spare", "maintenance", "decommissioned", name="lifecycle_status"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("librenms_device_id", sa.Integer(), nullable=True),
        sa.Column("prtg_object_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_internet_links_site_id"), "internet_links", ["site_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_internet_links_site_id"), table_name="internet_links")
    op.drop_table("internet_links")
    op.drop_index(op.f("ix_devices_site_id"), table_name="devices")
    op.drop_table("devices")
    op.drop_table("sites")
    sa.Enum(name="lifecycle_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="device_category").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
